name: Continuous Integration

concurrency:
  group: ci-${{ github.event.number }}
  cancel-in-progress: true

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    - cron: "31 1,12 * * *"

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  linter:
    if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && github.event.pull_request.draft == false)
    name: Linter
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  type-check:
    if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && github.event.pull_request.draft == false)
    name: Typecheck
    uses: ./.github/workflows/type-check.yml

  shellcheck:
    if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && github.event.pull_request.draft == false)
    name: Shellcheck
    uses: ./.github/workflows/shellcheck.yml

  markdownlint:
    if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && github.event.pull_request.draft == false)
    name: Markdownlint
    uses: ./.github/workflows/markdownlint.yml

  todo:
    if: github.event_name == 'push'
    name: TODO
    uses: ./.github/workflows/todo.yml

  pr-review:
    if: github.event_name == 'pull_request' && github.event.pull_request.draft == false
    name: Pull Request Validation
    uses: ./.github/workflows/pr-review.yml

  tests:
    if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && github.event.pull_request.draft == false)
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build --if-present
      - name: Run tests
        run: npm test

  coverage:
    needs: tests
    if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && github.event.pull_request.draft == false)
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Install
        run: npm ci
      - name: Run coverage
        env:
          CNA_SKIP_GIT: 1
          SKIP_SMOKE: 1
        run: npm run test:coverage
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: |
            coverage
            lcov.info
