name: Pull Request Validation

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: pr-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  pr-review:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Danger Files
        run: |
          echo "Setting up Danger files...";
          mv tools/danger/* .
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Lint (no autofix)
        run: npm run lint --workspaces --if-present
      - name: Type Check
        run: npm run type-check --if-present
      - name: Danger JS Action
        uses: actions/github-script@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const { execSync } = require('node:child_process');
            execSync('npx danger ci', { stdio: 'inherit' });
