name: Pull Request Validation

concurrency:
  group: pull_request_${{ github.event.number }}
  cancel-in-progress: true

on:
  workflow_call:

jobs:
  pr-review:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v3

      - name: Setup Danger Files
        run: |
          echo "Setting up Danger files..."
          mv tools/danger/* .

      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version

      - name: Install dependencies
        run: npm ci

      - name: Lint (no autofix)
        run: npm run lint --workspaces --if-present

      - name: Type Check
        run: npm run type-check --if-present

      - name: Danger JS Action
        uses: danger/danger-js@9.1.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
