name: Todo Checker

on:
  push:
    branches: [main]
  schedule:
    - cron: "31 1,12 * * *"
  workflow_dispatch:

permissions:
  contents: read
  issues: write

concurrency:
  group: todo-${{ github.ref }}
  cancel-in-progress: true

jobs:
  todo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: TODO to Issue
        uses: gr2m/todo-to-issue@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          close-issues: false
          identifiers: "TODO|FIXME|HACK"
