name: Typecheck

on:
  workflow_call:

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version

      - name: Install dependencies
        run: npm ci

      - name: Run type-check validation
        run: npm run type-check
